### ISSUE TITLE
Non spotify-auto related

### ISSUE THREAD

**Issue by 0wx** [cthuluhoop123/spotify-auto#1]
Hey, so I found out you're the author for [nhentai-js](https://npmjs.com/package/nhentai-js) right? So recently nhentai updated their website, it's small thing but make my bots cause some error.

I've several bots using your module, instead create my own it will be much better if you could update a little bit, it's really small fix, I want make a pull request to your module but I can't find the repo for it.

So here's the code you might use to fix the module
```
$('span').find('.count').replaceWith(function(){
   return ` (${this.children[0].data}) `;
});
```

Just put that on line 39 and everything will work fine again, thanks. It would be great for me or some other developer that using your module.

**Comment by dowzhong** [comment]
Thank you, I've updated the library to support the new redesign.

**Comment by dowzhong** [comment]
npm seems to not have updated the package's main page so use `npm i nhentai-js@4.0.0`

**Comment by 0wx** [comment]
> npm seems to not have updated the package's main page so use `npm i nhentai-js@4.0.0`

@cthuluhoop123 got it 👌
